pinterest-web/eslint-config-pinterest

- package.json
- rules/react.js
It might be nice to introduce linter rules one at a time, eventually getting to the nice state. Starting with this single rule to see what the workflow would be like.
> [React] Add component sorting.

- rules/react.js
Adding additional rules, commenting those that don't yet pass out.
All rules taken from: https://github.com/pinterest-web/eslint-config-pinterest/pull/5
> Add additional react rules.

- rules/react.js
> Enable JSX indentation rules.

- index.js
- package.json
> add semicolon rule pls

- index.js
- package.json
- rules/react.js
Revert to 1.1.0 to fix a few issues before we're ready to take these changes.
> Revert to 1.1.0

- index.js
- package.json
- rules/react.js
Relanding rules after temporary revert.
> Reland rules

- index.js
- package.json
Adds regexp to ignore import and require statements for the max-len rule
> Max len rule should ignore imports/requires

- README.md
- package.json
Rebasing https://github.com/pinterest-web/eslint-config-pinterest/pull/33 which never landed.
> Add badge, add repo url to package.json

- index.js
I have no idea what the 2 means, but this works
> Semis between ES6 class methods are bad

- .gitignore
- index.js
- package.json
This will enable sort-imports rule and bump config version to 26.0.0.
> Enabled sort-imports rule. Bumped version to 26.0.0

- index.js
- package.json
Forgot to bump version in the previous commit
> Bump version

- package.json
- rules/react.js
For compatibility with airbnb config
> Use double quotes for jsx props

- package.json
- rules/react.js
Forgot to add this rule to the config so it's just been chillin.
> Add no-dynamic-i18n-calls rule

- package.json
- rules/react.js
These additional options aren't supported anymore
> Fix unsupported react rules options

- index.js
- package.json
- rules/react.js
Warning for arrow-parens. Error for react/sort-comp.
> Warning for arrow-parens. Error for react/sort-comp.

- index.js
- package.json
> Warning for no-plusplus

- index.js
- package.json
Enable error for stateless component linter
> Enable error for stateless component linter

- index.js
- package.json
Enable semi-spacing, space-unary-ops, prefer-const, prefer-arrow-callback
> Enable semi-spacing, space-unary-ops, prefer-const, prefer-arrow-callback

- index.js
- package.json
Errors for one-var-declaration-per-line operator-assignment. Disable no-duplicate-imports
> Errors for one-var-declaration-per-line operator-assignment. Disable no-duplicate-imports

- index.js
- package.json
Warnings for consistent-return and Array-callback-return
> Warnings for consistent-return and Array-callback-return

- index.js
- package.json
https://github.com/yannickcr/eslint-plugin-react/issues/976
Too many false positives.
> Disable react/no-unused-prop-types
